name: Sigstore

on:
  push:
  workflow_dispatch:

jobs:
  sigstore-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: foo.txt
      - run: |
          git config --global user.name 'reandreev-asml'
          git config --global user.email '179727936+reandreev-asml@users.noreply.github.com'
          git add /home/runner/work/sigstore-test/sigstore-test/foo.txt.sigstore.json
          git commit -am "Update bundle"
          git push
